import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL = window.SUPABASE_URL || localStorage.getItem('SUPABASE_URL') || '';
const SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || localStorage.getItem('SUPABASE_ANON_KEY') || '';
const configured = SUPABASE_URL && SUPABASE_ANON_KEY;
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const ADMIN_EMAIL = 'info@iaac.in';
const PUBLIC_SITE_URL = 'https://portal.iaac.in';
const portal = location.pathname.startsWith('/admin') ? 'admin' : location.pathname.startsWith('/group') ? 'group' : 'home';
const portalUrl = (path = location.pathname) => new URL(path, location.origin === 'http://localhost:5173' ? location.origin : PUBLIC_SITE_URL).toString();
const detailColumns = ['group_name','country','city_region','leader_name','contact_email','whatsapp','delegation_size','performers','musicians','accompanying_members','category','performance_title','performance_duration','description','music_type','instruments','technical_requirements','food_preference','food_allergies','dietary_restrictions','food_requirements','remarks'];
const exportColumns = ['Group ID','Group Name','Country','City / Region','Leader / Contact','Email','WhatsApp / Mobile','Total Delegation Size','Performers','Musicians','Other Members','Performance Category','Performance Title','Duration','Description','Music','Instruments','Technical Requirements','Food Preference','Food Allergies','Dietary Restrictions','Other Food Requirements','Remarks','Submission Status','Arrival Flights','Departure Flights','MEA Participant Sheet Uploaded'];
const meaHeadings = ['S. No.','Full Name as per Passport','Gender','Date of Birth','Nationality','Passport Number','Passport Issue Date','Passport Expiry Date','Role'];
let state = { user:null, profile:null, view:'Dashboard', error:'', ok:'', apps:[], docs:[], app:null, groupIds:[], events:[], query:'', mode:'signin' };
const $ = (id)=>document.getElementById(id), esc=(s='')=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const groupRole=(role)=>role === 'group' || role === 'participant';
const gid=()=>state.profile?.group_ids?.code || 'Unclaimed';
const hasGroup=()=>Boolean(state.profile?.group_id);
function data(){ try{return JSON.parse(state.app?.notes || '{}')}catch{return {}} }
function flights(type){ return Array.isArray(data()[type]) ? data()[type] : [] }
function detailsComplete(){ const d=data(); return ['group_name','country','leader_name','contact_email','delegation_size','category','performance_title','food_preference'].every(k=>String(d[k]||'').trim()); }
function travelComplete(){ return flights('arrivals').length > 0 || flights('departures').length > 0; }
function docsComplete(){ return groupDocs().length > 0; }
function meaUploaded(){ return groupDocs().some(d=>/mea participant sheet/i.test(d.title)); }
function groupDocs(){ return state.docs.filter(d=>d.scope !== 'official'); }
async function safe(task){ state.error=''; state.ok=''; try{return await task()}catch(e){state.error=(e?.message || 'A network or database request failed.').replace(/invalid input syntax for type uuid: "null"/i,'This Group account has not claimed a Group ID yet.'); render();} }
function csvFile(columns, rows, name){ const text=[columns.join(','),...rows.map(r=>columns.map(c=>{const v=String(r[c]??'');return /[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}).join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'})); a.download=name; a.click(); }
function appPayload(extra={}){ return {id:state.app?.id,user_id:state.user.id,group_id:state.profile.group_id,team_name:extra.team_name ?? state.app?.team_name ?? '',country:extra.country ?? state.app?.country ?? '',category:extra.category ?? state.app?.category ?? 'Folk Dance',members:state.app?.members ?? '',media_links:state.app?.media_links ?? '',notes:JSON.stringify(extra.data ?? data()),status:extra.status ?? state.app?.status ?? 'Draft'}; }
async function init(){ if(!configured){render();return} supabase.auth.onAuthStateChange(async(event,session)=>{state.user=session?.user||null; state.profile=null; if(event==='PASSWORD_RECOVERY') state.mode='reset'; if(state.user && state.mode!=='reset') await loadProfile(); render();}); await safe(async()=>{ const {data,error}=await supabase.auth.getSession(); if(error) throw error; state.user=data.session?.user||null; if(state.user) await loadProfile(); }); render(); }
async function loadProfile(){ await safe(async()=>{ const {data,error}=await supabase.from('profiles').select('*, group_ids(code,status,is_test_reserved)').eq('id',state.user.id).maybeSingle(); if(error) throw error; if(!data) throw new Error('Your authentication account exists, but no portal profile was found. Ask an organiser to apply the latest Supabase migrations and backfill profiles.'); state.profile=data; state.view=data.role==='admin'?'Admin':'Dashboard'; }); }
async function refreshGroup(){ await safe(async()=>{ state.app=null; let r=await supabase.from('event_documents').select('*').or(`scope.eq.official,created_by.eq.${state.user.id}`).order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; if(!hasGroup()) return; r=await supabase.from('applications').select('*').eq('group_id',state.profile.group_id).maybeSingle(); if(r.error) throw r.error; state.app=r.data; }); }
async function refreshAdmin(){ await safe(async()=>{ let r=await supabase.from('applications').select('*, group_ids(code)').order('updated_at',{ascending:false}); if(r.error) throw r.error; state.apps=r.data||[]; r=await supabase.from('event_documents').select('*').order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; r=await supabase.from('group_ids').select('*').order('is_test_reserved',{ascending:false}).order('created_at',{ascending:true}); if(r.error) throw r.error; state.groupIds=r.data||[]; r=await supabase.from('group_id_events').select('*').order('created_at',{ascending:false}).limit(100); if(r.error) throw r.error; state.events=r.data||[]; }); }
window.nav=async(v)=>{state.view=v; if(state.profile?.role==='admin') await refreshAdmin(); else await refreshGroup(); render();};
window.toggleMenu=()=>{document.body.classList.toggle('showMenu'); render();};
window.signOut=()=>safe(()=>supabase.auth.signOut()); window.setMode=(m)=>{state.mode=m; state.error=''; state.ok=''; render();};
window.auth=async(e,mode)=>{e.preventDefault(); const f=new FormData(e.target), email=String(f.get('email')), password=String(f.get('password')), groupCode=String(f.get('group_id')||''); await safe(async()=>{ if(portal==='admin' && mode==='signup') throw new Error('Admin signup is not available from this portal.'); if(mode==='signup'){ if(email.trim().toLowerCase()===ADMIN_EMAIL) throw new Error('Admin accounts are provisioned separately. Use the Admin portal sign-in or password reset.'); if(!groupCode.trim()) throw new Error('A valid pre-created Group ID is required.'); const {data,error}=await supabase.auth.signUp({email,password,options:{data:{role:'group',group_id:groupCode.trim().toUpperCase()},emailRedirectTo:portalUrl('/group/')}}); if(error) throw error; if(data.session){ state.user=data.session.user; await loadProfile(); if(!state.profile?.group_id){ const r=await supabase.rpc('claim_group_id',{group_code:groupCode}); if(r.error) throw r.error; await loadProfile(); } state.ok='Group account created and Group ID claimed.'; } else { state.ok='Group account created. Check your email to confirm the account, then sign in from the Group Portal.'; state.mode='signin'; }} else {const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error) throw error; if(!data?.session?.user) throw new Error('Authentication succeeded but Supabase did not return a usable session. Please try again.'); state.user=data.session.user; state.profile=null; await loadProfile(); if(groupRole(state.profile?.role) && !state.profile?.group_id){const code=data.session.user.user_metadata?.group_id; if(code){const r=await supabase.rpc('claim_group_id',{group_code:code}); if(r.error) throw r.error; await loadProfile();}}}});};
window.requestReset=async(e)=>{e.preventDefault(); const email=new FormData(e.target).get('email'); await safe(async()=>{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:portalUrl(portal==='admin'?'/admin/':'/group/')}); if(error) throw error; state.ok='Password reset email sent. Open the link in that email to set a new password.'; state.mode='signin';});};
window.completeReset=async(e)=>{e.preventDefault(); const password=new FormData(e.target).get('password'); await safe(async()=>{const {error}=await supabase.auth.updateUser({password}); if(error) throw error; state.ok='Password updated. Please sign in with your new password.'; state.mode='signin'; await supabase.auth.signOut();});};
window.saveDetails=async(e)=>{e.preventDefault(); if(!hasGroup()) return safe(()=>Promise.reject(new Error('This Group account has not claimed a Group ID yet. Please contact the organisers.'))); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{const d={...data(),...Object.fromEntries(detailColumns.map(k=>[k,f[k]||'']))}; const payload=appPayload({team_name:d.group_name,country:d.country,category:d.category,data:d}); const {data:row,error}=await supabase.from('applications').upsert(payload,{onConflict:'group_id'}).select().single(); if(error) throw error; state.app=row; state.ok='Details saved.';});};
window.saveTravel=async(e)=>{e.preventDefault(); if(!hasGroup()) return safe(()=>Promise.reject(new Error('This Group account has not claimed a Group ID yet. Please contact the organisers.'))); const f=new FormData(e.target), d=data(), collect=(type)=>f.getAll(`${type}_date`).map((_,i)=>({date:f.getAll(`${type}_date`)[i]||'',time:f.getAll(`${type}_time`)[i]||'',airport:f.getAll(`${type}_airport`)[i]||'',flight_number:f.getAll(`${type}_flight`)[i]||'',people:f.getAll(`${type}_people`)[i]||''})).filter(x=>Object.values(x).some(Boolean)); d.arrivals=collect('arrival'); d.departures=collect('departure'); await safe(async()=>{const {data:row,error}=await supabase.from('applications').upsert(appPayload({data:d}),{onConflict:'group_id'}).select().single(); if(error) throw error; state.app=row; state.ok='Travel details saved.';});};
window.addFlight=(type)=>{const d=data(); d[type]=[...(Array.isArray(d[type])?d[type]:[]),{}]; state.app={...(state.app||{}),notes:JSON.stringify(d)}; render();};
window.removeFlight=(type,i)=>{const d=data(); d[type]=(Array.isArray(d[type])?d[type]:[]).filter((_,idx)=>idx!==i); state.app={...(state.app||{}),notes:JSON.stringify(d)}; render();};
window.uploadGroupDoc=async(e,type)=>{e.preventDefault(); if(!hasGroup()) return safe(()=>Promise.reject(new Error('This Group account has not claimed a Group ID yet. Please contact the organisers.'))); const f=new FormData(e.target), file=f.get('file'), path=`${state.profile.group_id}/${type}-${crypto.randomUUID()}-${file.name}`; await safe(async()=>{let r=await supabase.storage.from('event-documents').upload(path,file); if(r.error) throw r.error; const {data:url}=supabase.storage.from('event-documents').getPublicUrl(path); r=await supabase.from('event_documents').insert({title:type,description:file.name,scope:'group',group_id:state.profile.group_id,file_path:path,file_url:url.publicUrl,created_by:state.user.id}); if(r.error) throw r.error; e.target.reset(); await refreshGroup(); state.ok='Document uploaded.';});};
window.downloadMeaTemplate=()=>csvFile(meaHeadings, [], 'mea-participant-sheet-template.csv');
window.saveProfile=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{let r=await supabase.from('profiles').update({full_name:f.full_name,country:f.country}).eq('id',state.user.id); if(r.error) throw r.error; if(f.password){r=await supabase.auth.updateUser({password:f.password}); if(r.error) throw r.error;} state.ok='Profile updated.'; await loadProfile();});};
window.setStatus=async(id,status)=>safe(async()=>{const {error}=await supabase.from('applications').update({status}).eq('id',id); if(error) throw error; await refreshAdmin();});
window.uploadDoc=async(e)=>{e.preventDefault(); const f=new FormData(e.target), file=f.get('file'), path=`official/${crypto.randomUUID()}-${file.name}`; await safe(async()=>{let r=await supabase.storage.from('event-documents').upload(path,file); if(r.error) throw r.error; const {data}=supabase.storage.from('event-documents').getPublicUrl(path); r=await supabase.from('event_documents').insert({title:f.get('title'),description:f.get('description'),scope:'official',file_path:path,file_url:data.publicUrl,created_by:state.user.id}); if(r.error) throw r.error; e.target.reset(); await refreshAdmin();});};
window.deleteDoc=async(id,path)=>safe(async()=>{ if(path) await supabase.storage.from('event-documents').remove([path]); const {error}=await supabase.from('event_documents').delete().eq('id',id); if(error) throw error; await refreshAdmin();});
window.disableGroupId=async(id)=>{const reason=prompt('Reason for disabling/replacing this unclaimed Group ID?')||''; await safe(async()=>{const {error}=await supabase.rpc('admin_disable_group_id',{target_group_id:id,reason}); if(error) throw error; await refreshAdmin();});};
window.replaceGroupId=async(id)=>{const code=prompt('New replacement Group ID?'); if(!code) return; const reason=prompt('Replacement reason?')||''; await safe(async()=>{const {error}=await supabase.rpc('admin_replace_group_id',{old_group_id:id,new_code:code,reason}); if(error) throw error; await refreshAdmin();});};
window.exportRows=()=>{const rows=state.apps.map(a=>{const d=(()=>{try{return JSON.parse(a.notes||'{}')}catch{return {}}})(); return {'Group ID':a.group_ids?.code||a.group_id||'','Group Name':d.group_name||a.team_name||'','Country':d.country||a.country||'','City / Region':d.city_region||'','Leader / Contact':d.leader_name||'','Email':d.contact_email||'','WhatsApp / Mobile':d.whatsapp||'','Total Delegation Size':d.delegation_size||'','Performers':d.performers||'','Musicians':d.musicians||'','Other Members':d.accompanying_members||'','Performance Category':d.category||a.category||'','Performance Title':d.performance_title||'','Duration':d.performance_duration||'','Description':d.description||'','Music':d.music_type||'','Instruments':d.instruments||'','Technical Requirements':d.technical_requirements||'','Food Preference':d.food_preference||'','Food Allergies':d.food_allergies||'','Dietary Restrictions':d.dietary_restrictions||'','Other Food Requirements':d.food_requirements||'','Remarks':d.remarks||'','Submission Status':a.status||'Draft','Arrival Flights':JSON.stringify(d.arrivals||[]),'Departure Flights':JSON.stringify(d.departures||[]),'MEA Participant Sheet Uploaded':''};}); csvFile(exportColumns,rows,'festival-all-data.csv');};
window.exportMine=()=>csvFile(exportColumns,[{'Group ID':gid(),'Group Name':data().group_name||state.app?.team_name||'','Country':data().country||state.app?.country||'','Submission Status':state.app?.status||'Draft'}], 'my-group-submission.csv');
function shell(content){const isAdmin=state.profile.role==='admin', nav=isAdmin?['Admin','Groups','Documents','Profile']:['Dashboard','Group Details','Travel & Visa','Documents']; return `<header class="header"><div class="wrap bar"><button class="brand" onclick="nav('${isAdmin?'Admin':'Dashboard'}')"><small>portal.iaac.in</small><b>4th Parul University International Folklore Festival</b></button><nav class="nav">${nav.map(n=>`<button class="btn muted" onclick="nav('${n}')">${n}</button>`).join('')}</nav><button class="btn muted account" aria-label="Account menu" onclick="toggleMenu()">👤</button><div class="menu" ${document.body.classList.contains('showMenu')?'':'hidden'}><p>${esc(state.profile.email)}</p>${!isAdmin?`<p><small>Group ID</small><br><b>${esc(gid())}</b></p>`:`<span class="tag admin">Admin</span>`}${isAdmin?`<button class="btn muted" onclick="nav('Profile')">Profile Settings</button>`:''}<button class="btn danger" onclick="signOut()">Sign Out</button></div></div></header><main class="wrap">${notice()}${content}</main>`}
function notice(){return `${state.error?`<p class="error">${esc(state.error)}</p>`:''}${state.ok?`<p class="ok">${esc(state.ok)}</p>`:''}`}
function landing(){return `<main class="wrap hero"><section><p class="gold">portal.iaac.in</p><h1>International Folklore Festival Portal</h1><p>Sign in through the portal for your account type.</p></section><section class="card stack"><a class="btn primary center" href="/group/">Group Portal</a><a class="btn muted center" href="/admin/">Admin Portal</a></section></main>`}
function authPage(){ if(portal==='home') return landing(); const label=portal==='admin'?'Admin':'Group'; if(state.mode==='forgot') return `<main class="wrap hero"><section><p class="gold">${label} password recovery</p><h1>Reset your festival portal password</h1></section><form class="card stack" onsubmit="requestReset(event)">${notice()}<input name="email" type="email" placeholder="${label} account email" required><button class="btn primary">Send reset email</button><button type="button" class="btn muted" onclick="setMode('signin')">Back to sign in</button></form></main>`; if(state.mode==='reset') return `<main class="wrap hero"><section><p class="gold">${label} password reset</p><h1>Complete password reset</h1></section><form class="card stack" onsubmit="completeReset(event)">${notice()}<input name="password" type="password" minlength="6" placeholder="New password" required><button class="btn primary">Update password</button></form></main>`; const signin=`<form class="stack" onsubmit="auth(event,'signin')"><h2>${label} Sign In</h2>${notice()}<input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="6" placeholder="Password" required><button class="btn primary">Sign In</button><button type="button" class="link" onclick="setMode('forgot')">Forgot password?</button></form>`; const signup=portal==='group'?`<form class="stack" onsubmit="auth(event,'signup')"><h2>Create Group account</h2><input name="email" type="email" placeholder="Group account email" required><input name="password" type="password" minlength="6" placeholder="Password" required><input name="group_id" placeholder="Pre-created Group ID" required><button class="btn muted">Claim Group ID & Sign Up</button></form>`:''; return `<main class="wrap hero"><section><p class="gold">${portal==='admin'?'Admin Portal':'Group Portal'}</p><h1>International Folklore Festival Portal</h1><p>${portal==='admin'?'Organizer sign-in only. There is no public Admin signup here.':'Use your Group account to sign in or create your account with the Group ID provided by the organisers.'}</p></section><section class="card"><div class="grid">${signin}${signup}</div></section></main>`}
function unclaimed(){return `<section class="card"><h2>Group ID Unclaimed</h2><p>This Group account is signed in, but it is not associated with a Group ID yet. Please contact the organisers with your account email.</p><p><b>Account email:</b> ${esc(state.profile.email)}</p></section>`}
function groupDashboard(){ if(state.view==='Documents') return docs(); if(state.view==='Travel & Visa') return travelVisa(); if(state.view==='Group Details') return groupDetails(); if(!hasGroup()) return unclaimed(); const d=data(), status=state.app?.status||'Draft'; return `<div class="grid cols"><section class="card"><h2>Dashboard</h2><p><b>Group name:</b> ${esc(d.group_name||state.app?.team_name||'Not provided')}</p><p><b>Country:</b> ${esc(d.country||state.app?.country||'Not provided')}</p><p><b>Group ID:</b> ${esc(gid())}</p><p><b>Submission status:</b> <span class="tag status">${esc(status)}</span></p></section><section class="card span2"><h2>Completion Summary</h2><p>Group Details: <span class="tag status">${detailsComplete()?'Complete':'Incomplete'}</span></p><p>Travel Details: <span class="tag status">${travelComplete()?'Complete':'Incomplete'}</span></p><p>Documents: <span class="tag status">${docsComplete()?'Complete':'Incomplete'}</span></p><p>MEA Participant Sheet: <span class="tag status">${meaUploaded()?'Uploaded':'Not uploaded'}</span></p></section></div>`}
function groupDetails(){ if(!hasGroup()) return unclaimed(); const d=data(); return `<form class="card stack" onsubmit="saveDetails(event)"><h2>Group Details</h2><h3>Group Information</h3><div class="grid cols">${input('group_name',d.group_name,'Official group name')}${input('country',d.country,'Country')}${input('city_region',d.city_region,'City / region')}${input('leader_name',d.leader_name,'Group leader / contact person')}${input('contact_email',d.contact_email || state.profile.email,'Email','email')}${input('whatsapp',d.whatsapp,'WhatsApp / mobile')}${input('delegation_size',d.delegation_size,'Total delegation size','number')}${input('performers',d.performers,'Number of performers','number')}${input('musicians',d.musicians,'Number of musicians','number')}${input('accompanying_members',d.accompanying_members,'Other accompanying members','number')}</div><h3>Performance Information</h3><div class="grid cols">${input('category',d.category,'Performance type / category')}${input('performance_title',d.performance_title,'Performance title / name')}${input('performance_duration',d.performance_duration,'Approximate performance duration')}<select name="music_type"><option value="">Music: Live / Recorded</option>${['Live','Recorded','Mixed'].map(x=>`<option ${d.music_type===x?'selected':''}>${x}</option>`).join('')}</select>${area('description',d.description,'Short description')}${area('instruments',d.instruments,'Instruments')}${area('technical_requirements',d.technical_requirements,'Technical requirements')}</div><h3>Food</h3><div class="grid cols"><select name="food_preference"><option value="">Food preference</option>${['Vegetarian','Non-vegetarian','Mixed'].map(x=>`<option ${d.food_preference===x?'selected':''}>${x}</option>`).join('')}</select>${area('food_allergies',d.food_allergies,'Food allergies')}${area('dietary_restrictions',d.dietary_restrictions,'Dietary restrictions')}${area('food_requirements',d.food_requirements,'Other food requirements')}</div><h3>Remarks</h3>${area('remarks',d.remarks,'Special requirements / other remarks')}<button class="btn primary">Save Details</button></form>`}
function flightRows(type,label){ const arr=flights(type); const prefix=type==='arrivals'?'arrival':'departure'; return `<section class="card stack"><h2>${label}</h2>${arr.map((f,i)=>`<div class="grid cols flight"><input name="${prefix}_date" type="date" value="${esc(f.date)}"><input name="${prefix}_time" type="time" value="${esc(f.time)}"><input name="${prefix}_airport" placeholder="Airport" value="${esc(f.airport)}"><input name="${prefix}_flight" placeholder="Flight Number" value="${esc(f.flight_number)}"><input name="${prefix}_people" type="number" min="0" placeholder="Number of People" value="${esc(f.people)}"><button type="button" class="btn danger" onclick="removeFlight('${type}',${i})">Remove</button></div>`).join('')||'<p>No flights added yet.</p>'}<button type="button" class="btn muted" onclick="addFlight('${type}')">+ Add ${type==='arrivals'?'Arrival':'Departure'} Flight</button></section>`}
function travelVisa(){ if(!hasGroup()) return unclaimed(); return `<form class="stack" onsubmit="saveTravel(event)"><section class="card"><h2>Travel & Visa</h2><p>Travel and visa information for participating groups will be provided here.</p></section>${flightRows('arrivals','Arrival Flights')}${flightRows('departures','Departure Flights')}<button class="btn primary">Save Travel Details</button></form>`}
function docs(){ const official=state.docs.filter(d=>d.scope==='official'), mine=groupDocs(); const uploads=['Participation Agreement','Flight Itinerary','MEA Participant Sheet','Other Document']; return `<section class="card stack"><h2>Documents</h2><button class="btn primary" onclick="downloadMeaTemplate()">Download MEA Participant Sheet Template</button>${hasGroup()?`<div class="grid cols">${uploads.map(t=>`<form class="card stack" onsubmit="uploadGroupDoc(event,'${t}')"><h3>${t}</h3><input name="file" type="file" required><button class="btn muted">Upload</button></form>`).join('')}</div>`:'<p>Document uploads are available after your Group ID is claimed.</p>'}<h3>Your uploaded documents</h3>${mine.map(d=>`<a class="doc" target="_blank" href="${esc(d.file_url)}"><b>${esc(d.title)}</b><p>${esc(d.description||'')}</p></a>`).join('')||'<p>No group documents uploaded yet.</p>'}<h3>Official event documents</h3>${official.map(d=>`<a class="doc" target="_blank" href="${esc(d.file_url)}"><b>📄 ${esc(d.title)}</b><p>${esc(d.description||'')}</p></a>`).join('')||'<p>No official documents available yet.</p>'}</section>`}
function admin(){ if(state.view==='Documents') return adminDocs(); if(state.view==='Profile') return profile(); if(state.view==='Groups') return groups(); const rows=state.apps.filter(a=>JSON.stringify(a).toLowerCase().includes(state.query.toLowerCase())); return `<section class="card"><h2>All Group Submissions</h2><button class="btn primary" onclick="exportRows()">Export All Data (CSV)</button><input placeholder="Search and filter" oninput="state.query=this.value;render()"><div class="scroll"><table><thead><tr><th>Group</th><th>Country</th><th>Category</th><th>Status</th><th>Approval</th></tr></thead><tbody>${rows.map(a=>{const d=(()=>{try{return JSON.parse(a.notes||'{}')}catch{return {}}})();return `<tr><td>${esc(d.group_name||a.team_name)}</td><td>${esc(d.country||a.country)}</td><td>${esc(d.category||a.category)}</td><td>${esc(a.status)}</td><td><select onchange="setStatus('${a.id}',this.value)"><option>${esc(a.status)}</option><option>Draft</option><option>Submitted</option><option>Under Review</option><option>Approved</option><option>Rejected</option></select></td></tr>`}).join('')}</tbody></table></div></section>`}
function groups(){return `<section class="card"><h2>Group ID Management</h2><p>Issue additional Group IDs in Supabase by inserting rows into <code>group_ids</code>; reserved test IDs are clearly marked and are not production Group IDs.</p><div class="scroll"><table><thead><tr><th>Group ID</th><th>Status</th><th>Claimed</th><th>Replacement</th><th>Actions</th></tr></thead><tbody>${state.groupIds.map(g=>`<tr><td>${esc(g.code)} ${g.is_test_reserved?'<span class="tag admin">TEST / RESERVED</span>':''}</td><td>${esc(g.status)}</td><td>${g.claimed_by?'Yes':'No'}</td><td>${g.replaced_by?'Yes':'No'}</td><td><button class="btn danger" onclick="disableGroupId('${g.id}')">Disable</button> <button class="btn muted" onclick="replaceGroupId('${g.id}')">Replace</button></td></tr>`).join('')}</tbody></table></div><h3>Recent Group ID History</h3>${state.events.map(ev=>`<p class="doc"><b>${esc(ev.event_type)}</b> ${esc(ev.created_at)}</p>`).join('')}</section>`}
function adminDocs(){return `<section class="card stack"><h2>Organizer Document Upload</h2><form class="grid cols" onsubmit="uploadDoc(event)"><input name="title" placeholder="Title" required><input name="description" placeholder="Description"><input name="file" type="file" required><button class="btn primary">Upload</button></form>${state.docs.map(d=>`<p class="doc"><a href="${esc(d.file_url)}">${esc(d.title)}</a> <button class="btn danger" onclick="deleteDoc('${d.id}','${esc(d.file_path||'')}')">Delete</button></p>`).join('')}</section>`}
function profile(){return `<form class="card stack" onsubmit="saveProfile(event)"><h2>Profile Settings</h2><p>${esc(state.profile.email)} <span class="tag ${state.profile.role==='admin'?'admin':'group'}">${state.profile.role==='admin'?'Admin':'Group'}</span></p>${input('full_name',state.profile.full_name,'Display/contact name')}${input('country',state.profile.country,'Country')}<input name="password" type="password" placeholder="New password (optional)"><button class="btn primary">Save</button></form>`}
function input(n,v,p,t='text'){return `<input name="${n}" type="${t}" value="${esc(v||'')}" placeholder="${p}">`} function area(n,v,p){return `<textarea name="${n}" placeholder="${p}">${esc(v||'')}</textarea>`}
function render(){ if(!configured){$('app').innerHTML='<main class="wrap card"><h1>Configuration required</h1><p>Set SUPABASE_URL and SUPABASE_ANON_KEY globally or in localStorage. Apply the Supabase migration before launch.</p></main>';return} if(!state.user || state.mode==='forgot' || state.mode==='reset'){$('app').innerHTML=authPage();return} if(!state.profile){$('app').innerHTML=`<main class="wrap card"><h1>Loading profile…</h1>${notice()}<p>If this does not finish, the Supabase profile trigger/backfill migration may not have been applied.</p><button class="btn danger" onclick="signOut()">Sign Out</button></main>`;return} if(portal==='admin' && state.profile.role!=='admin'){$('app').innerHTML='<main class="wrap card"><h1>Admin Portal</h1><p>This entry point is only for Admin accounts. Group users must use /group.</p><button class="btn danger" onclick="signOut()">Sign Out</button></main>';return} if(portal==='group' && state.profile.role==='admin'){$('app').innerHTML='<main class="wrap card"><h1>Group Portal</h1><p>This entry point is only for Group accounts. Admin users must use /admin.</p><button class="btn danger" onclick="signOut()">Sign Out</button></main>';return} if(portal==='home'){$('app').innerHTML=landing();return} if(groupRole(state.profile.role) && ['Admin','Groups','Profile'].includes(state.view)) state.view='Dashboard'; $('app').innerHTML=shell(state.profile.role==='admin'?admin():groupDashboard()); }
window.state=state; window.render=render; init();
