import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL = window.SUPABASE_URL || localStorage.getItem('SUPABASE_URL') || '';
const SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || localStorage.getItem('SUPABASE_ANON_KEY') || '';
const configured = SUPABASE_URL && SUPABASE_ANON_KEY;
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const ADMIN_CODE = 'PU-FOLKLORE-2026';
let state = { user:null, profile:null, view:'Dashboard', error:'', ok:'', apps:[], docs:[], app:null, query:'' };
const $ = (id)=>document.getElementById(id); const esc=(s='')=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function adminSignup(email, code){ return email.trim().toLowerCase()==='info@iaac.in' || code.trim()===ADMIN_CODE; }
async function safe(task){ state.error=''; state.ok=''; try{return await task()}catch(e){state.error=e?.message || 'A network or database request failed.'; render();} }
function csv(rows,name){ const keys=Object.keys(rows[0]||{}); const text=[keys.join(','),...rows.map(r=>keys.map(k=>{const v=String(r[k]??'');return /[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}).join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'})); a.download=name; a.click(); }
async function init(){ if(!configured){render();return} const {data}=await supabase.auth.getUser(); state.user=data.user; if(state.user) await loadProfile(); supabase.auth.onAuthStateChange(async(_e,s)=>{state.user=s?.user||null; state.profile=null; if(state.user) await loadProfile(); render();}); render(); }
async function loadProfile(){ await safe(async()=>{ const {data,error}=await supabase.from('profiles').select('*').eq('id',state.user.id).single(); if(error) throw error; state.profile=data; state.view=data.role==='admin'?'Admin':'Dashboard'; }); }
async function refreshParticipant(){ await safe(async()=>{ let r=await supabase.from('applications').select('*').eq('user_id',state.user.id).maybeSingle(); if(r.error) throw r.error; state.app=r.data; r=await supabase.from('event_documents').select('*').order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; }); }
async function refreshAdmin(){ await safe(async()=>{ let r=await supabase.from('applications').select('*').order('updated_at',{ascending:false}); if(r.error) throw r.error; state.apps=r.data||[]; r=await supabase.from('event_documents').select('*').order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; }); }
window.nav=async(v)=>{state.view=v; if(state.profile?.role==='admin') await refreshAdmin(); else await refreshParticipant(); render();};
window.signOut=()=>safe(()=>supabase.auth.signOut());
window.auth=async(e,mode)=>{e.preventDefault(); const f=new FormData(e.target), email=f.get('email'), password=f.get('password'), role=adminSignup(email,f.get('access')||'')?'admin':'participant'; await safe(async()=>{ if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{role}}}); if(error) throw error; if(data.user){const up=await supabase.from('profiles').upsert({id:data.user.id,email,role}); if(up.error) throw up.error;}} else {const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) throw error;}});};
window.saveApp=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{const {data,error}=await supabase.from('applications').upsert({...f,id:state.app?.id,user_id:state.user.id},{onConflict:'user_id'}).select().single(); if(error) throw error; state.app=data; state.ok='Application saved.';});};
window.saveProfile=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{let r=await supabase.from('profiles').update({full_name:f.full_name,country:f.country}).eq('id',state.user.id); if(r.error) throw r.error; if(f.password){r=await supabase.auth.updateUser({password:f.password}); if(r.error) throw r.error;} state.ok='Profile updated.'; await loadProfile();});};
window.setStatus=async(id,status)=>{ await safe(async()=>{const {error}=await supabase.from('applications').update({status}).eq('id',id); if(error) throw error; await refreshAdmin();});};
window.uploadDoc=async(e)=>{e.preventDefault(); const f=new FormData(e.target), file=f.get('file'), path=`${crypto.randomUUID()}-${file.name}`; await safe(async()=>{let r=await supabase.storage.from('event-documents').upload(path,file); if(r.error) throw r.error; const {data}=supabase.storage.from('event-documents').getPublicUrl(path); r=await supabase.from('event_documents').insert({title:f.get('title'),description:f.get('description'),file_path:path,file_url:data.publicUrl,created_by:state.user.id}); if(r.error) throw r.error; e.target.reset(); await refreshAdmin();});};
window.deleteDoc=async(id,path)=>{await safe(async()=>{ if(path) await supabase.storage.from('event-documents').remove([path]); const {error}=await supabase.from('event_documents').delete().eq('id',id); if(error) throw error; await refreshAdmin();});};
window.exportRows=()=>csv(state.apps,'festival-all-data.csv'); window.exportMine=()=>csv([state.app||{status:'Draft',user_id:state.user.id}], 'my-application.csv');
function shell(content){return `<header class="header"><div class="wrap bar"><button class="brand" onclick="nav('${state.profile.role==='admin'?'Admin':'Dashboard'}')"><small>festival.iaac.in</small><b>4th Parul University International Folklore Festival</b></button><nav class="nav">${(state.profile.role==='admin'?['Admin','Documents','Profile']:['Dashboard','Submit','Documents','Profile']).map(n=>`<button class="btn muted" onclick="nav('${n}')">${n}</button>`).join('')}</nav><button class="btn muted" onclick="document.body.classList.toggle('showMenu')">👤</button><div class="menu" ${document.body.classList.contains('showMenu')?'':'hidden'}><p>${esc(state.profile.email)}</p><span class="tag ${state.profile.role}">${state.profile.role}</span><button class="btn muted" onclick="nav('Profile')">Profile Settings</button><button class="btn danger" onclick="signOut()">Sign Out</button></div></div></header><main class="wrap">${notice()}${content}</main>`}
function notice(){return `${state.error?`<p class="error">${esc(state.error)}</p>`:''}${state.ok?`<p class="ok">${esc(state.ok)}</p>`:''}`}
function authPage(){return `<main class="wrap hero"><section><p class="gold">IAAC × Parul University</p><h1>International Folklore Festival Portal</h1><p>Secure participant submissions, organizer documents, approvals, and exports for the 2026 festival.</p></section><section class="card"><div class="grid"><form class="stack" onsubmit="auth(event,'signin')"><h2>Sign in</h2>${notice()}<input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="6" placeholder="Password" required><button class="btn primary">Sign In</button></form><form class="stack" onsubmit="auth(event,'signup')"><h2>Create account</h2><input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="6" placeholder="Password" required><input name="access" placeholder="Admin access code (optional)"><button class="btn muted">Sign Up</button></form></div></section></main>`}
function participant(){ if(state.view==='Documents') return docs(); if(state.view==='Profile') return profile(); const a=state.app||{}; return `<div class="grid cols"><section class="card"><h2>Application Overview</h2><p>Status <span class="tag status">${esc(a.status||'Draft')}</span></p><button class="btn primary" onclick="exportMine()">Download my summary</button></section><form class="card stack span2" onsubmit="saveApp(event)"><h2>Step-by-step Submission Portal</h2>${input('team_name',a.team_name,'Team name')}${input('country',a.country,'Country')}<select name="category"><option>Folk Dance</option><option>Folk Music</option><option>Traditional Theatre</option><option>Craft & Costume Showcase</option></select>${area('members',a.members,'Member roster')}${area('media_links',a.media_links,'Media links')}${area('notes',a.notes,'Notes')}<select name="status"><option>Draft</option><option>Submitted</option></select><button class="btn primary">Save application</button></form></div>`}
function admin(){ if(state.view==='Documents') return adminDocs(); if(state.view==='Profile') return profile(); const rows=state.apps.filter(a=>JSON.stringify(a).toLowerCase().includes(state.query.toLowerCase())); return `<section class="card"><h2>Participant Management</h2><button class="btn primary" onclick="exportRows()">Export All Data (CSV)</button><input placeholder="Search and filter" oninput="state.query=this.value;render()"><div class="scroll"><table><thead><tr><th>Team</th><th>Country</th><th>Category</th><th>Status</th><th>Approval</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.team_name)}</td><td>${esc(a.country)}</td><td>${esc(a.category)}</td><td>${esc(a.status)}</td><td><select onchange="setStatus('${a.id}',this.value)"><option>Under Review</option><option>Approved</option><option>Rejected</option></select></td></tr>`).join('')}</tbody></table></div></section>`}
function docs(){return `<section class="card"><h2>Official Event Documents</h2><div class="grid cols">${state.docs.map(d=>`<a class="doc" target="_blank" href="${esc(d.file_url)}"><b>📄 ${esc(d.title)}</b><p>${esc(d.description||'')}</p></a>`).join('')}</div></section>`}
function adminDocs(){return `<section class="card stack"><h2>Organizer Document Upload</h2><form class="grid cols" onsubmit="uploadDoc(event)"><input name="title" placeholder="Title" required><input name="description" placeholder="Description"><input name="file" type="file" required><button class="btn primary">Upload</button></form>${state.docs.map(d=>`<p class="doc"><a href="${esc(d.file_url)}">${esc(d.title)}</a> <button class="btn danger" onclick="deleteDoc('${d.id}','${esc(d.file_path||'')}')">Delete</button></p>`).join('')}</section>`}
function profile(){return `<form class="card stack" onsubmit="saveProfile(event)"><h2>Profile Settings</h2><p>${esc(state.profile.email)} <span class="tag ${state.profile.role}">${state.profile.role}</span></p>${input('full_name',state.profile.full_name,'Full name')}${input('country',state.profile.country,'Country')}<input name="password" type="password" placeholder="New password (optional)"><button class="btn primary">Save</button></form>`}
function input(n,v,p){return `<input name="${n}" value="${esc(v||'')}" placeholder="${p}" required>`} function area(n,v,p){return `<textarea name="${n}" placeholder="${p}">${esc(v||'')}</textarea>`}
function render(){ if(!configured){$('app').innerHTML='<main class="wrap card"><h1>Configuration required</h1><p>Set SUPABASE_URL and SUPABASE_ANON_KEY globally or in localStorage. Apply the Supabase migration before launch.</p></main>';return} if(!state.user){$('app').innerHTML=authPage();return} if(!state.profile){$('app').innerHTML='<main class="wrap">Loading profile…</main>';return} $('app').innerHTML=shell(state.profile.role==='admin'?admin():participant()); }
window.state=state; window.render=render; init();
