import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL = window.SUPABASE_URL || localStorage.getItem('SUPABASE_URL') || '';
const SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || localStorage.getItem('SUPABASE_ANON_KEY') || '';
const configured = SUPABASE_URL && SUPABASE_ANON_KEY;
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const ADMIN_EMAIL = 'info@iaac.in';
const portal = location.pathname.startsWith('/admin') ? 'admin' : location.pathname.startsWith('/group') ? 'group' : 'home';
let state = { user:null, profile:null, view:'Dashboard', error:'', ok:'', apps:[], docs:[], app:null, groupIds:[], events:[], query:'', mode:'signin' };
const $ = (id)=>document.getElementById(id), esc=(s='')=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const groupRole=(role)=>role === 'group' || role === 'participant';
async function safe(task){ state.error=''; state.ok=''; try{return await task()}catch(e){state.error=e?.message || 'A network or database request failed.'; render();} }
function csv(rows,name){ const keys=Object.keys(rows[0]||{}); const text=[keys.join(','),...rows.map(r=>keys.map(k=>{const v=String(r[k]??'');return /[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}).join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'})); a.download=name; a.click(); }
async function init(){ if(!configured){render();return} supabase.auth.onAuthStateChange(async(event,session)=>{state.user=session?.user||null; state.profile=null; if(event==='PASSWORD_RECOVERY') state.mode='reset'; if(state.user && state.mode!=='reset') await loadProfile(); render();}); const {data}=await supabase.auth.getUser(); state.user=data.user; if(state.user) await loadProfile(); render(); }
async function loadProfile(){ await safe(async()=>{ const {data,error}=await supabase.from('profiles').select('*, group_ids(code,status,is_test_reserved)').eq('id',state.user.id).single(); if(error) throw error; state.profile=data; state.view=data.role==='admin'?'Admin':'Dashboard'; }); }
async function refreshGroup(){ await safe(async()=>{ let r=await supabase.from('applications').select('*').eq('group_id',state.profile.group_id).maybeSingle(); if(r.error) throw r.error; state.app=r.data; r=await supabase.from('event_documents').select('*').order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; }); }
async function refreshAdmin(){ await safe(async()=>{ let r=await supabase.from('applications').select('*').order('updated_at',{ascending:false}); if(r.error) throw r.error; state.apps=r.data||[]; r=await supabase.from('event_documents').select('*').order('created_at',{ascending:false}); if(r.error) throw r.error; state.docs=r.data||[]; r=await supabase.from('group_ids').select('*').order('is_test_reserved',{ascending:false}).order('created_at',{ascending:true}); if(r.error) throw r.error; state.groupIds=r.data||[]; r=await supabase.from('group_id_events').select('*').order('created_at',{ascending:false}).limit(100); if(r.error) throw r.error; state.events=r.data||[]; }); }
window.nav=async(v)=>{state.view=v; if(state.profile?.role==='admin') await refreshAdmin(); else await refreshGroup(); render();};
window.signOut=()=>safe(()=>supabase.auth.signOut()); window.setMode=(m)=>{state.mode=m; render();};
window.auth=async(e,mode)=>{e.preventDefault(); const f=new FormData(e.target), email=String(f.get('email')), password=String(f.get('password')), groupCode=String(f.get('group_id')||''); await safe(async()=>{ if(portal==='admin' && mode==='signup') throw new Error('Admin signup is not available from this portal.'); if(mode==='signup'){ if(email.trim().toLowerCase()===ADMIN_EMAIL) throw new Error('Admin accounts are provisioned separately. Use the Admin portal sign-in or password reset.'); if(!groupCode.trim()) throw new Error('A valid pre-created Group ID is required.'); const {data,error}=await supabase.auth.signUp({email,password,options:{data:{role:'group'}}}); if(error) throw error; if(data.user){let r=await supabase.from('profiles').upsert({id:data.user.id,email,role:'group'}); if(r.error) throw r.error; r=await supabase.rpc('claim_group_id',{group_code:groupCode}); if(r.error) throw r.error; state.ok='Group account created and Group ID claimed. Check your email if confirmation is required.';}} else {const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) throw error;}});};
window.requestReset=async(e)=>{e.preventDefault(); const email=new FormData(e.target).get('email'); await safe(async()=>{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.href}); if(error) throw error; state.ok='Password reset email sent. Open the link in that email to set a new password.'; state.mode='signin';});};
window.completeReset=async(e)=>{e.preventDefault(); const password=new FormData(e.target).get('password'); await safe(async()=>{const {error}=await supabase.auth.updateUser({password}); if(error) throw error; state.ok='Password updated. Please sign in with your new password.'; state.mode='signin'; await supabase.auth.signOut();});};
window.saveApp=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{if(!state.profile.group_id) throw new Error('This account has not claimed a Group ID.'); const payload={...f,id:state.app?.id,user_id:state.user.id,group_id:state.profile.group_id}; const {data,error}=await supabase.from('applications').upsert(payload,{onConflict:'group_id'}).select().single(); if(error) throw error; state.app=data; state.ok='Group submission saved.';});};
window.saveProfile=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); await safe(async()=>{let r=await supabase.from('profiles').update({full_name:f.full_name,country:f.country}).eq('id',state.user.id); if(r.error) throw r.error; if(f.password){r=await supabase.auth.updateUser({password:f.password}); if(r.error) throw r.error;} state.ok='Profile updated.'; await loadProfile();});};
window.setStatus=async(id,status)=>safe(async()=>{const {error}=await supabase.from('applications').update({status}).eq('id',id); if(error) throw error; await refreshAdmin();});
window.uploadDoc=async(e)=>{e.preventDefault(); const f=new FormData(e.target), file=f.get('file'), path=`${crypto.randomUUID()}-${file.name}`; await safe(async()=>{let r=await supabase.storage.from('event-documents').upload(path,file); if(r.error) throw r.error; const {data}=supabase.storage.from('event-documents').getPublicUrl(path); r=await supabase.from('event_documents').insert({title:f.get('title'),description:f.get('description'),scope:'official',file_path:path,file_url:data.publicUrl,created_by:state.user.id}); if(r.error) throw r.error; e.target.reset(); await refreshAdmin();});};
window.deleteDoc=async(id,path)=>safe(async()=>{ if(path) await supabase.storage.from('event-documents').remove([path]); const {error}=await supabase.from('event_documents').delete().eq('id',id); if(error) throw error; await refreshAdmin();});
window.disableGroupId=async(id)=>{const reason=prompt('Reason for disabling/replacing this unclaimed Group ID?')||''; await safe(async()=>{const {error}=await supabase.rpc('admin_disable_group_id',{target_group_id:id,reason}); if(error) throw error; await refreshAdmin();});};
window.replaceGroupId=async(id)=>{const code=prompt('New replacement Group ID?'); if(!code) return; const reason=prompt('Replacement reason?')||''; await safe(async()=>{const {error}=await supabase.rpc('admin_replace_group_id',{old_group_id:id,new_code:code,reason}); if(error) throw error; await refreshAdmin();});};
window.exportRows=()=>csv(state.apps,'festival-all-data.csv'); window.exportMine=()=>csv([state.app||{status:'Draft',group_id:state.profile?.group_id}], 'my-group-submission.csv');
function shell(content){const isAdmin=state.profile.role==='admin', nav=isAdmin?['Admin','Groups','Documents','Profile']:['Dashboard','Submit','Documents','Profile']; return `<header class="header"><div class="wrap bar"><button class="brand" onclick="nav('${isAdmin?'Admin':'Dashboard'}')"><small>festival.iaac.in</small><b>4th Parul University International Folklore Festival</b></button><nav class="nav">${nav.map(n=>`<button class="btn muted" onclick="nav('${n}')">${n}</button>`).join('')}</nav><button class="btn muted" onclick="document.body.classList.toggle('showMenu')">👤</button><div class="menu" ${document.body.classList.contains('showMenu')?'':'hidden'}><p>${esc(state.profile.email)}</p><span class="tag ${isAdmin?'admin':'group'}">${isAdmin?'Admin':'Group'}</span>${state.profile.group_ids?.code?`<p><small>Group ID ${esc(state.profile.group_ids.code)} ${state.profile.group_ids.is_test_reserved?'(TEST / RESERVED)':''}</small></p>`:''}<button class="btn muted" onclick="nav('Profile')">Profile Settings</button><button class="btn danger" onclick="signOut()">Sign Out</button></div></div></header><main class="wrap">${notice()}${content}</main>`}
function notice(){return `${state.error?`<p class="error">${esc(state.error)}</p>`:''}${state.ok?`<p class="ok">${esc(state.ok)}</p>`:''}`}
function landing(){return `<main class="wrap hero"><section><p class="gold">festival.iaac.in</p><h1>International Folklore Festival Portal</h1><p>Choose the correct secure entry point for your account type.</p></section><section class="card stack"><a class="btn primary center" href="/group/">Group Portal</a><a class="btn muted center" href="/admin/">Admin Portal</a></section></main>`}
function authPage(){ if(portal==='home') return landing(); const label=portal==='admin'?'Admin':'Group'; if(state.mode==='forgot') return `<main class="wrap hero"><section><p class="gold">${label} password recovery</p><h1>Reset your festival portal password</h1></section><form class="card stack" onsubmit="requestReset(event)">${notice()}<input name="email" type="email" placeholder="${label} account email" required><button class="btn primary">Send reset email</button><button type="button" class="btn muted" onclick="setMode('signin')">Back to sign in</button></form></main>`; if(state.mode==='reset') return `<main class="wrap hero"><section><p class="gold">${label} password reset</p><h1>Complete password reset</h1></section><form class="card stack" onsubmit="completeReset(event)">${notice()}<input name="password" type="password" minlength="6" placeholder="New password" required><button class="btn primary">Update password</button></form></main>`; const signin=`<form class="stack" onsubmit="auth(event,'signin')"><h2>${label} Sign In</h2>${notice()}<input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="6" placeholder="Password" required><button class="btn primary">Sign In</button><button type="button" class="link" onclick="setMode('forgot')">Forgot password?</button></form>`; const signup=portal==='group'?`<form class="stack" onsubmit="auth(event,'signup')"><h2>Create Group account</h2><input name="email" type="email" placeholder="Group account email" required><input name="password" type="password" minlength="6" placeholder="Password" required><input name="group_id" placeholder="Pre-created Group ID" required><p><small>Use <b>PUIFF26-TEST01</b> only for organiser testing; it is reserved and not a production Group ID.</small></p><button class="btn muted">Claim Group ID & Sign Up</button></form>`:''; return `<main class="wrap hero"><section><p class="gold">${portal==='admin'?'Admin Portal':'Group Portal'}</p><h1>International Folklore Festival Portal</h1><p>${portal==='admin'?'Organizer sign-in only. There is no public Admin signup here.':'Groups sign in or create an account with a valid pre-created Group ID. There is no Admin signup here.'}</p></section><section class="card"><div class="grid">${signin}${signup}</div></section></main>`}
function groupDashboard(){ if(state.view==='Documents') return docs(); if(state.view==='Profile') return profile(); const a=state.app||{}; return `<div class="grid cols"><section class="card"><h2>Group Overview</h2><p>Group ID <span class="tag group">${esc(state.profile.group_ids?.code||'Unclaimed')}</span> ${state.profile.group_ids?.is_test_reserved?'<span class="tag admin">TEST / RESERVED</span>':''}</p><p>Status <span class="tag status">${esc(a.status||'Draft')}</span></p><button class="btn primary" onclick="exportMine()">Download my group summary</button></section><form class="card stack span2" onsubmit="saveApp(event)"><h2>Group Submission Portal</h2>${input('team_name',a.team_name,'Group name')}${input('country',a.country,'Country')}<select name="category"><option>Folk Dance</option><option>Folk Music</option><option>Traditional Theatre</option><option>Craft & Costume Showcase</option></select>${area('members',a.members,'Participant roster')}${area('media_links',a.media_links,'Media links')}${area('notes',a.notes,'Notes and document links') }<select name="status"><option>Draft</option><option>Submitted</option></select><button class="btn primary">Save group submission</button></form></div>`}
function admin(){ if(state.view==='Documents') return adminDocs(); if(state.view==='Profile') return profile(); if(state.view==='Groups') return groups(); const rows=state.apps.filter(a=>JSON.stringify(a).toLowerCase().includes(state.query.toLowerCase())); return `<section class="card"><h2>All Group Submissions</h2><button class="btn primary" onclick="exportRows()">Export All Data (CSV)</button><input placeholder="Search and filter" oninput="state.query=this.value;render()"><div class="scroll"><table><thead><tr><th>Group</th><th>Country</th><th>Category</th><th>Status</th><th>Approval</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.team_name)}</td><td>${esc(a.country)}</td><td>${esc(a.category)}</td><td>${esc(a.status)}</td><td><select onchange="setStatus('${a.id}',this.value)"><option>${esc(a.status)}</option><option>Under Review</option><option>Approved</option><option>Rejected</option></select></td></tr>`).join('')}</tbody></table></div></section>`}
function groups(){return `<section class="card"><h2>Group ID Management</h2><p>Issue additional Group IDs in Supabase by inserting rows into <code>group_ids</code>; reserved test IDs are clearly marked and are not production Group IDs.</p><div class="scroll"><table><thead><tr><th>Group ID</th><th>Status</th><th>Claimed</th><th>Replacement</th><th>Actions</th></tr></thead><tbody>${state.groupIds.map(g=>`<tr><td>${esc(g.code)} ${g.is_test_reserved?'<span class="tag admin">TEST / RESERVED</span>':''}</td><td>${esc(g.status)}</td><td>${g.claimed_by?'Yes':'No'}</td><td>${g.replaced_by?'Yes':'No'}</td><td><button class="btn danger" onclick="disableGroupId('${g.id}')">Disable</button> <button class="btn muted" onclick="replaceGroupId('${g.id}')">Replace</button></td></tr>`).join('')}</tbody></table></div><h3>Recent Group ID History</h3>${state.events.map(ev=>`<p class="doc"><b>${esc(ev.event_type)}</b> ${esc(ev.created_at)}</p>`).join('')}</section>`}
function docs(){return `<section class="card"><h2>Official Event Documents</h2><div class="grid cols">${state.docs.map(d=>`<a class="doc" target="_blank" href="${esc(d.file_url)}"><b>📄 ${esc(d.title)}</b><p>${esc(d.description||'')}</p></a>`).join('')}</div></section>`}
function adminDocs(){return `<section class="card stack"><h2>Organizer Document Upload</h2><form class="grid cols" onsubmit="uploadDoc(event)"><input name="title" placeholder="Title" required><input name="description" placeholder="Description"><input name="file" type="file" required><button class="btn primary">Upload</button></form>${state.docs.map(d=>`<p class="doc"><a href="${esc(d.file_url)}">${esc(d.title)}</a> <button class="btn danger" onclick="deleteDoc('${d.id}','${esc(d.file_path||'')}')">Delete</button></p>`).join('')}</section>`}
function profile(){return `<form class="card stack" onsubmit="saveProfile(event)"><h2>Profile Settings</h2><p>${esc(state.profile.email)} <span class="tag ${state.profile.role==='admin'?'admin':'group'}">${state.profile.role==='admin'?'Admin':'Group'}</span></p>${input('full_name',state.profile.full_name,'Display/contact name')}${input('country',state.profile.country,'Country')}<input name="password" type="password" placeholder="New password (optional)"><button class="btn primary">Save</button></form>`}
function input(n,v,p){return `<input name="${n}" value="${esc(v||'')}" placeholder="${p}" required>`} function area(n,v,p){return `<textarea name="${n}" placeholder="${p}">${esc(v||'')}</textarea>`}
function render(){ if(!configured){$('app').innerHTML='<main class="wrap card"><h1>Configuration required</h1><p>Set SUPABASE_URL and SUPABASE_ANON_KEY globally or in localStorage. Apply the Supabase migration before launch.</p></main>';return} if(!state.user || state.mode==='forgot' || state.mode==='reset'){$('app').innerHTML=authPage();return} if(!state.profile){$('app').innerHTML='<main class="wrap">Loading profile…</main>';return} if(portal==='admin' && state.profile.role!=='admin'){$('app').innerHTML='<main class="wrap card"><h1>Admin Portal</h1><p>This entry point is only for Admin accounts. Group users must use /group.</p><button class="btn danger" onclick="signOut()">Sign Out</button></main>';return} if(portal==='group' && state.profile.role==='admin'){$('app').innerHTML='<main class="wrap card"><h1>Group Portal</h1><p>This entry point is only for Group accounts. Admin users must use /admin.</p><button class="btn danger" onclick="signOut()">Sign Out</button></main>';return} if(portal==='home'){$('app').innerHTML=landing();return} if(groupRole(state.profile.role) && ['Admin','Groups'].includes(state.view)) state.view='Dashboard'; $('app').innerHTML=shell(state.profile.role==='admin'?admin():groupDashboard()); }
window.state=state; window.render=render; init();
